#!/usr/bin/env bash
#### artillery x4 config  module
####
#### Based on work of:
#### Raymond Himle and meteyou
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2021 - 2022
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces

# Source error handling, leave this in place
set -Ee

# Set LC_ALL to prevent errors
export LC_ALL=C

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Copy files"
unpack /filesystem/home/"${BASE_USER}" /home/"${BASE_USER}" "${BASE_USER}"

echo_green "Setup host firmware/service"
# Disable real-time throttling TODO: check if really necessary or set via kernel
echo -e "\nkernel.sched_rt_runtime_us = -1\n" >> /etc/sysctl.d/10-disable-rt-group-limit.conf
pushd /home/"${BASE_USER}"/klipper &> /dev/null || exit 1
sudo -u "${BASE_USER}" cp config_host .config
sudo -u "${BASE_USER}" make flash -j
[ -d "/etc/systemd/system" ] && cp ./scripts/klipper-mcu.service /etc/systemd/system/
systemctl_if_exists enable klipper-mcu.service
popd &> /dev/null || exit 1

echo_green "Test mcu firmware builds"
pushd /home/"${BASE_USER}"/klipper &> /dev/null || exit 1
sudo -u "${BASE_USER}" make clean 
sudo -u "${BASE_USER}" cp config_mcu .config
sudo -u "${BASE_USER}" make -j
popd &> /dev/null || exit 1

echo_green "Configure Artillery X4"
ln -s /home/"${BASE_USER}"/klipper/config/printer-artillery-sidewinder-x4-hw.cfg /home/"${BASE_USER}"/printer_data/config/printer_hw.cfg
ln -s /home/"${BASE_USER}"/klipper/config/printer-artillery-sidewinder-x4-macros.cfg /home/"${BASE_USER}"/printer_data/config/macros.cfg

echo_green "Finished artillery x4 configuration"
