#!/usr/bin/env bash
# Shebang for better file detection
#### mainsail module config
####
#### Based on work of:
#### Raymond Himle and meteyou
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2021 - 2022
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

[[ -n "${KLIPPERLCD_PKGS}" ]] || KLIPPERLCD_PKGS="python3-serial python3-requests"

# Support for the stock display computer
#[[ -n "$KLIPPERLCD_REPO_SHIP" ]] || KLIPPERLCD_REPO_SHIP="https://github.com/joakimtoe/KlipperLCD.git"
#[[ -n "$KLIPPERLCD_REPO_BRANCH" ]] || KLIPPERLCD_REPO_BRANCH="master"

export KLIPPERLCD_PKGS