#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces
BASE_ARCH="arm64"

# Image source
DOWNLOAD_BASE_URL="https://github.com/eazrael/armbian-build-artillery-x4/releases/download/24.5.2/Armbian_24.5.2_Artilleryx4_bookworm_current_6.6.35-20240623165711.img.xz"
DOWNLOAD_URL_CHECKSUM="${DOWNLOAD_BASE_URL}.sha"
DOWNLOAD_URL_IMAGE="${DOWNLOAD_BASE_URL}"
BASE_IMAGE_ENLARGEROOT=4000


### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_PRETTY_SBC_NAME="Artillery3D X4"
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC="artillery3d-x4"

KLIPPER_REPO_SHIP="https://github.com/eazrael/klipper.git"
KLIPPER_REPO_BRANCH="artilleryx4"

MODULES="base(pkgupgrade,udev_fix,armbian(armbian_net,mainsailos,klipper,is_req_preinstall,moonraker,mainsail,timelapse,crowsnest,sonar,artilleryx4config))"


# export Variables
export BASE_ARCH
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
export KLIPPER_REPO_BRANCH
export KLIPPER_REPO_SHIP
export MAKEFLAGS
export MODULES
