#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

get_version() {
    local ver
    ver="$(realpath "$( dirname -- "${BASH_SOURCE[0]}")"/../src/version)"

    if [ -f "${ver}" ]; then
        cat "${ver}"
        return
    fi

    ver="$(realpath "$( dirname -- "${BASH_SOURCE[0]}")"/version)"
    cat "${ver}"
}

get_img_name() {
    local -a types
    types=(zip 7z xz)
    if [ -n "${DIST_PATH}" ]; then
        for i in "${types[@]}"; do
            find "${DIST_PATH}/image/" -type f -name "*.${i}" -printf "%p\n"
        done
    fi

    if [ -z "${DIST_PATH}" ]; then
        echo ""
    fi
}

DIST_VERSION="$(get_version)"
BASE_ZIP_IMG="$(get_img_name)"
DIST_NAME="MainsailOS"

BASE_BOOT_MOUNT_PATH=boot

# export Variables
export BASE_BOOT_MOUNT_PATH
export DIST_NAME
export DIST_VERSION
export BASE_ZIP_IMG

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_PRETTY_NAME="Mainsail OS"
# shellcheck disable=SC2034
JSON_DESCRIPTION="A OS image with Klipper/Moonraker/Mainsail preinstalled for your 3D printers"
# shellcheck disable=SC2034
JSON_ICON_URL="https://os.mainsail.xyz/rpi-imager.png"
# shellcheck disable=SC2034
JSON_INIT_FORMAT="none"
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC=""
# JSON_SUPPORTED_SBC="pi1-32bit pi2-32bit pi3-32bit pi3-64bit pi4-32bit pi4-64bit pi5-64bit"
#!/usr/bin/env bash
# Shebang for better file detection

# Declare Variables before exporting.
# See https://www.shellcheck.net/wiki/SC2155

# Download Base Url
DOWNLOAD_BASE_URL="https://github.com/mainsail-crew/armbian-builds/releases/latest/download"

# Base User
BASE_ADD_USER="yes"
BASE_USER="pi"
BASE_USER_PASSWORD="armbian"

# Needed while building for non rpi sbc
BASE_DISTRO="armbian"
BASE_IMAGE_RASPBIAN="no"

# partition resizing
BASE_ROOT_PARTITION="2"
BASE_IMAGE_ENLARGEROOT=2500
BASE_IMAGE_RESIZEROOT=600
# Compress not needed due compression done in workflow
BASE_RELEASE_COMPRESS=no
# Modules are valid for 32bit and 64bit images
MODULES="base(pkgupgrade,udev_fix,armbian(armbian_net,mainsailos,klipper,is_req_preinstall,moonraker,mainsail,timelapse,crowsnest,sonar))"

# export Variables
export DOWNLOAD_BASE_URL
export BASE_ADD_USER
export BASE_USER
export BASE_USER_PASSWORD
export BASE_DISTRO
export BASE_IMAGE_RASPBIAN
export BASE_ROOT_PARTITION
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export BASE_RELEASE_COMPRESS
export MODULES

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_DESCRIPTION="A port of Armbian with preinstalled Klipper/Moonraker/Mainsail for 3D printers"
#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces
BASE_ARCH="arm64"

# Image source
DOWNLOAD_BASE_URL="https://evilazrael.net/tmp/armbian"
DOWNLOAD_URL_CHECKSUM="${DOWNLOAD_BASE_URL}/Armbian_24.5.0-trunk_Artilleryx4_bookworm_current_6.6.31.img.xz.sha"
DOWNLOAD_URL_IMAGE="${DOWNLOAD_BASE_URL}/Armbian_24.5.0-trunk_Artilleryx4_bookworm_current_6.6.31.img.xz"

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_PRETTY_SBC_NAME="Artillery3D X4"
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC="artillery3d-x4"

KLIPPER_REPO_SHIP="https://github.com/eazrael/klipper.git"
KLIPPER_REPO_BRANCH="artilleryx4"

MODULES="base(pkgupgrade,udev_fix,armbian(armbian_net,mainsailos,klipper,is_req_preinstall,moonraker,mainsail,timelapse,crowsnest,sonar,artilleryx4config))"
export MODULES

MAKEFLAGS="-j"

BASE_IMAGE_ENLARGEROOT=0
BASE_IMAGE_RESIZEROOT=0

# export Variables
export BASE_ARCH
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
export KLIPPER_REPO_BRANCH
export KLIPPER_REPO_SHIP
export MAKEFLAGS
export MODULES

